spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/book_manager?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      username: root
      password: kkpig1484

    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      defer-datasource-initialization: true
      generate-ddl: true
      hibernate:
        ddl-auto: create-drop
    sql:
      init:
        mode: always

server:
  port: 9090